# Generated by Django 4.2.3 on 2023-10-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('discription', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'lassi'), ('MS', 'MilkShake'), ('PN', 'Panner'), ('GH', 'Ghee'), ('GH', 'Ghee'), ('CH', 'Cheese'), ('Ic', 'IceCreame')], max_length=2)),
                ('product_img', models.ImageField(upload_to='Product')),
            ],
        ),
    ]
